sudo: required
dist: trusty
matrix:
  fast_finish: true
language: php
php:
  - 5.6
  - 7.0
  - 7.1

addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

services:
  - docker
  - postgresql

env:
  global:
  - PHP_COVERAGE=TRUE
  - TEST_JS=FALSE
  matrix:
  - CORE_BRANCH=master   DB=sqlite
  - CORE_BRANCH=master   DB=pgsql
  # Uncomment when nc13 is out
  #- CORE_BRANCH=stable12 DB=sqlite
  #- CORE_BRANCH=stable12 DB=mysql
  #- CORE_BRANCH=stable12 DB=pgsql

matrix:
  include:
    - env: "CORE_BRANCH=master DB=mysql TEST_JS=TRUE"
  fast_finish: true

branches:
  only:
  - master
  - "/^stable\\d+(\\.\\d+)?$/"
  - /^v\d++(\.\d+)?+(\.\d+)?+(\.\d+)?$/

cache:
  directories:
  - "$HOME/.composer/cache/files"
  - "$HOME/.npm"
  - "$HOME/.cache/bower"

before_install:
  - php --info

  # Install composer deps
  - composer install

  # XDebug is only needed if we report coverage -> speeds up other builds
  - if [[ "$PHP_COVERAGE" = "FALSE" ]]; then phpenv config-rm xdebug.ini; fi

  # Set up DB
  - if [[ "$DB" == 'pgsql' ]]; then createuser -U travis -s nc_autotest; fi
  - if [[ "$DB" == 'mysql' ]]; then mysql -u root -e 'create database nc_autotest;'; fi
  - if [[ "$DB" == 'mysql' ]]; then mysql -u root -e "CREATE USER 'nc_autotest'@'localhost' IDENTIFIED BY '';"; fi
  - if [[ "$DB" == 'mysql' ]]; then mysql -u root -e "GRANT ALL ON nc_autotest.* TO 'nc_autotest'@'localhost';"; fi

  - sh -c "if [ '$TEST_JS' = 'TRUE' ]; then npm install; fi"

  - cd ..
  - git clone https://github.com/nextcloud/server.git --recursive --depth 1 -b $CORE_BRANCH core
  - mv twofactor_u2f core/apps/

before_script:
  # Set up core
  - php -f core/occ maintenance:install --database-name nc_autotest --database-user nc_autotest --admin-user admin --admin-pass admin --database $DB --database-pass=''

  # Set up app
  - php -f core/occ app:enable twofactor_u2f
  - cd core/apps/twofactor_u2f

script:
  # Check PHP syntax errors
  - find . -name \*.php -not -path './vendor/*' -exec php -l "{}" \;

  # Run server's app code checker
  #- php ../../occ app:check-code twofactor_u2f

  # Run JS tests
  - sh -c "if [ '$TEST_JS' = 'TRUE' ]; then ./node_modules/karma/bin/karma start --single-run; fi"
  - sh -c "if [ '$TEST_JS' = 'TRUE' ]; then cat ./coverage/*/lcov.info | ./node_modules/coveralls/bin/coveralls.js; fi"

  # Run PHP tests
  - cd tests
  - ../vendor/phpunit/phpunit/phpunit --configuration phpunit.xml

  # Publish PHP coverage to scrutinizer
  - if [[ "$PHP_COVERAGE" = "TRUE" ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [[ "$PHP_COVERAGE" = "TRUE" ]]; then php ocular.phar code-coverage:upload --format=php-clover clover.xml; fi
