sudo: required
dist: xenial
language: php
php:
  - 7.2
  - 7.3
  - 7.4

addons:
  # Server requires PostgreSQL >= 9.5
  postgresql: "9.5"
  apt:
    packages:
    - libxml2-utils

services:
  - docker
  - mysql
  - postgresql

env:
  global:
  - PHP_COVERAGE=FALSE
  - TEST_JS=FALSE
  - CORE_BRANCH=master
  - DB=sqlite
  - PATCH_VERSION_CHECK=FALSE

matrix:
  include:
    - php: 7.2
      env: "DB=mysql PHP_COVERAGE=TRUE"
    - php: 7.2
      env: "DB=mysql TEST_JS=TRUE"
    - php: 7.3
      env: "DB=pgsql"
    - php: 7.3
      env: "CORE_BRANCH=stable17"
    - php: 7.3
      env: "CORE_BRANCH=stable18"
    - php: nightly
      env: "PATCH_VERSION_CHECK=TRUE"
  fast_finish: true
  allow_failures:
    - php: nightly

branches:
  only:
  - master
  - "/^stable\\d+(\\.\\d+)?+(\\.\\d+)?$/"
  - /^v\d++(\.\d+)?+(\.\d+)?+(\.\d+)?$/

cache:
  directories:
  - "$HOME/.composer/cache/files"
  - "$HOME/.npm"
  - "$HOME/.cache/bower"

before_install:
  - php --info

  # Install composer deps
  - composer install

  # XDebug is only needed if we report coverage -> speeds up other builds (7.3 has no xdebug yet)
  - if [[ "$PHP_COVERAGE" = "FALSE" ]]; then phpenv config-rm xdebug.ini || true; fi

  # Use latest node for js tests
  - if [[ "$TEST_JS" = "TRUE" ]]; then nvm install node; fi

  # Set up DB
  - if [[ "$DB" == 'pgsql' ]]; then createuser -U travis -s nc_autotest; fi
  - if [[ "$DB" == 'mysql' ]]; then mysql -u root -e 'create database nc_autotest;'; fi
  - if [[ "$DB" == 'mysql' ]]; then mysql -u root -e "CREATE USER 'nc_autotest'@'localhost' IDENTIFIED BY '';"; fi
  - if [[ "$DB" == 'mysql' ]]; then mysql -u root -e "GRANT ALL ON nc_autotest.* TO 'nc_autotest'@'localhost';"; fi

  - sh -c "if [ '$TEST_JS' = 'TRUE' ]; then npm install; fi"

  - cd ..
  - git clone https://github.com/nextcloud/server.git --recursive --depth 1 -b $CORE_BRANCH core
  - if [[ "$PATCH_VERSION_CHECK" = "TRUE" ]]; then echo "<?php" > core/lib/versioncheck.php; fi
  - if [[ "$PATCH_VERSION_CHECK" = "TRUE" ]]; then  sed -ri 's/(<php min\-version="[0-9\.]+") max\-version="[0-9\.]+"/\1/g' twofactor_u2f/appinfo/info.xml; fi
  - mv twofactor_u2f core/apps/

before_script:
  # Set up core
  - php -f core/occ maintenance:install --database-name nc_autotest --database-user nc_autotest --admin-user admin --admin-pass admin --database $DB --database-pass=''

  # Set up app
  - php -f core/occ app:enable twofactor_u2f
  - cd core/apps/twofactor_u2f

script:
  # Check info.xml schema validity
  - wget https://apps.nextcloud.com/schema/apps/info.xsd
  - xmllint appinfo/info.xml --schema info.xsd --noout
  - rm info.xsd

  # Check PHP syntax errors
  - composer run lint

  # Run server's app code checker
  #- php ../../occ app:check-code twofactor_u2f

  # Run JS tests
  - sh -c "if [ '$TEST_JS' = 'TRUE' ]; then npm run build; fi"
  - sh -c "if [ '$TEST_JS' = 'TRUE' ]; then npm run test; fi"
  - sh -c "if [ '$TEST_JS' = 'TRUE' ]; then npm run coverage; fi"

  # Run PHP tests
  - composer run test

  # Publish PHP coverage to scrutinizer
  - if [[ "$PHP_COVERAGE" = "TRUE" ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [[ "$PHP_COVERAGE" = "TRUE" ]]; then php ocular.phar code-coverage:upload --format=php-clover clover.xml; fi
